env: 
  browser: true
  es2021: true
extends: 
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
parserOptions: 
  ecmaVersion: 12
  sourceType: module
  parser: babel-eslint
plugins:
  - prettier
rules: {}